server:
  port: 9527

spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  profiles:
    active: prod
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://175.178.127.92:3373/stu_attendence?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: renrenzi
    password: 123456a!
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    database: 0
    host: 175.178.127.92
    port: 6379
    password: wBa3u2KqvDKET.B
  rabbitmq:
    host: 175.178.127.92
    username: admin
    port: 5672
    password: 123456
    publisher-returns: true
mybatis-plus:
  type-aliases-package: com.jj.stu.attendance.admim.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl